### ISSUE TITLE
Rick roll not displaying

### ISSUE THREAD

**Issue by zombiestruck** [sorenrehkopf/custom-rick-roll#1]
On changing the video from ./assets/nggyunglud.mp4 to /assets/nggyunglud.mp4 it works. It just requires something to update the source for it to load. Upon changing it back to ,/assets/nggyunglud.mp4 it reloads.

**Comment by rptoma** [comment]
Can confirm that all the generated URLs have a black video.

**Comment by MrSpark333** [comment]
It happened to me also. But I realize the video was there/ But it wasn't auto-playing. But clicking with right button I could choose to play the video _(And pause it)_.

**Comment by Judjim** [comment]
It seems like Chrome doesn't autoplay, but IE and Edge do. :-(

**Comment by CromebookCoder** [comment]
I attempted to rick roll my friend and it didn't show

**Comment by sorenrehkopf** [comment]
Hello! I am just now seeing these and have not been aware that anyone was really using the site. I can repro the issue and will get it fixed soon.
Sorry for the delay everyone and thanks for reporting!

**Comment by CromebookCoder** [comment]
Ty

**Comment by sorenrehkopf** [comment]
This issue should now be resolved. Unfortunately I had to change the experience a bit due to a policy for chrome that went into effect since I was last working on this that prevents autoplaying videos with sound, and requires user interaction before a video can be played via JS. Users will now see a fake "accept our cookies" message which will trigger the video when interacted with.
