### ISSUE TITLE
I can pause the video, why?

### ISSUE THREAD

**Issue by ZaldyColinares** [sorenrehkopf/custom-rick-roll#20]
![Screenshot_2021-01-19-10-44-06-06_f936c31d0041139c630017c44e194ebf](https://user-images.githubusercontent.com/55983382/104981358-6a708600-5a43-11eb-85dc-055a8c08a658.jpg)

**Comment by sorenrehkopf** [comment]
Hey @ZaldyColinares! 

Thanks for reporting! That is unexpected and unintended. Do you have your device and browser information?

Full disclaimer I very rarely work on this project but if you leave device / browser info and a few repro steps I'll look into it next time I get around to making updates.

Thanks!

**Comment by ZaldyColinares** [comment]
Well, I used Samsung Internet Explorer

**Comment by Boptima** [comment]
I can also pause the video if I use tab to select the pause button. Works on edge and firefox

**Comment by ghost** [comment]
Pretty sure it is designed for Chromium based browsers.

**Comment by remenkemi** [comment]
> 
> 
> Pretty sure it is designed for Chromium based browsers.

Samsung Internet is Chromium based and Firefox isn't. Yet it works in Firefox but not Samsung Internet.

**Comment by markkhoo** [comment]
> I can also pause the video if I use tab to select the pause button. Works on edge and firefox

Yea tabbing through to pause still works. But I feel like this is fine. I don't think the average user would immediately think about tabbing right as they are getting Rick Rolled.

**Comment by sorenrehkopf** [comment]
Hey everyone, since it sounds like this is based on using keyboard controls to access the video controls, I'm gonna go ahead and close this out. 

As @markkhoo correctly calls out, it's not the end of the world if the user is able to tab and pause the video. It's really not even the end of the world if they're able to pause the video normally to be entirely honest, and I may just remove that text from the generated pages since it has led to people opening these kinds of issues.

The main point is just to play the video without people realizing it. As long as that happens then they've been rolled. 👍
