### ISSUE TITLE
Wrong url

### ISSUE THREAD

**Issue by Mineboi** [sorenrehkopf/custom-rick-roll#24]
The link said free robux

**Comment by ghost** [comment]
?

**Comment by JohnB17** [comment]
I think they mean they made a link for something, but it said free robux instead of what they chose.
Or, they got trolled.

**Comment by Rexogamer** [comment]
...they got trolled :p

**Comment by sorenrehkopf** [comment]
Sorry it's taken me so long to reply to this, I was confused about what the issue was here, but I believe the comments above are probably correct, and we may have found the remaining person on the internet who doesn't know what rick rolling is. 🎉 🌟

This is a monumentous discovery and I'm so proud to have taken part. 

For @Mineboi, I believe the page was working as intended so I'm gonna close this. 

Here's a helpful article to explain. https://www.sanfransentinel.com/a-brief-history-of-rick-rolling.html

**Comment by ghost** [comment]
You got me :P
