### ISSUE TITLE
Disable right-click to remove user controls

### ISSUE THREAD

**Issue by kstuddard** [sorenrehkopf/custom-rick-roll#8]
(At least in Firefox,) if you right-click the video you can still pause the video, and have other controls as well.

**Comment by sorenrehkopf** [comment]
Hey @kstuddard ! Tbh I'm honestly not really concerned about it. The main concept is to get the video to start playing without people expecting it not to force them to watch the entire thing. They can of course also just close the window if they want it to stop.

I'm guessing that the right click controls may be an intentional thing on the part of FF to give the user some mechanism to control the playback even without html controls as video playback on websites can definitely be a source of irritation in most contexts. 

If you figure out a way to get them to go away in ff though then I can implement next time I make updates! Feel free to re-open this issue with an example in the future if so as I'm gonna close this for now since I don't plan to investigate on my own.

Thanks for reporting though!

**Comment by bc-185** [comment]
> 
> 
> Hey @kstuddard ! Tbh I'm honestly not really concerned about it. The main concept is to get the video to start playing without people expecting it not to force them to watch the entire thing. They can of course also just close the window if they want it to stop.
> 
> I'm guessing that the right click controls may be an intentional thing on the part of FF to give the user some mechanism to control the playback even without html controls as video playback on websites can definitely be a source of irritation in most contexts.
> 
> If you figure out a way to get them to go away in ff though then I can implement next time I make updates! Feel free to re-open this issue with an example in the future if so as I'm gonna close this for now since I don't plan to investigate on my own.
> 
> Thanks for reporting though!

To disable right click, simply add this to the body:
`oncontextmenu="return false;"`
